import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { set } from "zod";

export default function Home() {
  const [time, setTime] = useState({ h: 0, m: 0, s: 0 });
  const [alarm, setAlarm] = useState({ h: 0, m: 0 });
  const currentTime = () => {
    const currTime = new Date();
    setTime({
      h: currTime.getHours(),
      m: currTime.getMinutes(),
      s: currTime.getSeconds(),
    });
  };
  setInterval(currentTime, 1000);

  return (
    <>
      <Head>
        <title>Alarmi</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center gap-5 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-10">
        {/* ----- SA3A ----- */}
        <div>
          <div className="grid auto-cols-max grid-flow-col gap-5 text-center">
            <div className="rounded-box flex flex-col bg-white/10 p-2 text-neutral-content backdrop-blur-lg">
              <span className="countdown font-mono text-5xl">
                <span style={{ "--value": time.h }}></span>
              </span>
              hours
            </div>
            <div className="rounded-box flex flex-col bg-white/10 p-2 text-neutral-content backdrop-blur-lg">
              <span className="countdown font-mono text-5xl">
                <span style={{ "--value": time.m }}></span>
              </span>
              min
            </div>
            <div className="rounded-box flex flex-col bg-white/10 p-2 text-neutral-content backdrop-blur-lg">
              <span className="countdown font-mono text-5xl">
                <span style={{ "--value": time.s }}></span>
              </span>
              sec
            </div>
          </div>
        </div>
        {/* ----- SA3A ----- */}
        <div>
          <div>
            <div className="join join-vertical lg:join-horizontal">
              <button className="btn join-item">Button</button>
              <button className="btn join-item">Button</button>
              <button className="btn join-item">Button</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
